
CREATE TABLE PIZZERIA (
                ID_PIZZERIA VARCHAR NOT NULL,
                ADRESS VARCHAR NOT NULL,
                ID_FOURNISSEUR INT NOT NULL,
                NOM_FOURNISSEUR VARCHAR(30) NOT NULL,
                NUMBER_EMPLOYÉS INT NOT NULL,
                CODE_POSTAL CHAR(5) NOT NULL,
                NOM VARCHAR NOT NULL,
                PRIMARY KEY (ID_PIZZERIA, ADRESS, ID_FOURNISSEUR, NOM_FOURNISSEUR)
);


CREATE UNIQUE INDEX pizzeria_idx
 ON PIZZERIA
 ( CODE_POSTAL ASC, NOM );

CREATE TABLE PAIEMENT_EXTERNE (
                ID_VERSEMENT INT NOT NULL,
                ID_FOURNISSEUR INT NOT NULL,
                NOM_SOCIÉTÉ VARCHAR(30) NOT NULL,
                COUTS DECIMAL NOT NULL,
                NUMERO_COMMANDE VARCHAR NOT NULL,
                DATE TIME NOT NULL,
                PRIMARY KEY (ID_VERSEMENT, ID_FOURNISSEUR, NOM_SOCIÉTÉ)
);


CREATE TABLE INGREDIENTS (
                ID_INGRÉDIENTS INT NOT NULL,
                NOM VARCHAR NOT NULL,
                PRIX_100G VARCHAR NOT NULL,
                PRIMARY KEY (ID_INGRÉDIENTS, NOM)
);


CREATE TABLE RECETTES (
                ID_RECETTES INT AUTO_INCREMENT NOT NULL,
                DISPONIBILITÉS BOOLEAN NOT NULL,
                NOM VARCHAR NOT NULL,
                INGREDIENTS VARCHAR NOT NULL,
                PRIX CHAR(3) NOT NULL,
                PRIMARY KEY (ID_RECETTES)
);


CREATE TABLE PIZZA_CATEGORIE (
                ID INT NOT NULL,
                NAME_CATEGORIES VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE TABLE STOCK (
                ID_FOURNISSEUR INT NOT NULL,
                NOM_FOURNISSEUR VARCHAR(30) NOT NULL,
                CATEGORIE_INGREDIENT VARCHAR NOT NULL,
                ID_INGRÉDIENTS INT NOT NULL,
                NOM_INGRÉDIENTS VARCHAR NOT NULL,
                Disponibilités BOOLEAN NOT NULL,
                Quantité VARCHAR(50) NOT NULL,
                PRIMARY KEY (ID_FOURNISSEUR, NOM_FOURNISSEUR, CATEGORIE_INGREDIENT, ID_INGRÉDIENTS, NOM_INGRÉDIENTS)
);


CREATE TABLE EMPLOYÉS (
                ID_EMPLOYES INT NOT NULL,
                ID_PIZZERIA VARCHAR NOT NULL,
                ADRESS_TRAVAIL VARCHAR NOT NULL,
                NOM VARCHAR(50) NOT NULL,
                PRENOM VARCHAR(50) NOT NULL,
                ROLES VARCHAR(50) NOT NULL,
                AGE INT NOT NULL,
                PRIMARY KEY (ID_EMPLOYES, ID_PIZZERIA, ADRESS_TRAVAIL)
);


CREATE TABLE PIZZA (
                ID_PIZZA INT AUTO_INCREMENT NOT NULL,
                ID_CATEGORIES INT NOT NULL,
                ID_RECETTES INT NOT NULL,
                NOM_INGRÉDIENTS VARCHAR NOT NULL,
                ID_EMPLOYES INT NOT NULL,
                ID_PIZZERIA VARCHAR NOT NULL,
                ADRESS_TRAVAIL VARCHAR NOT NULL,
                PRIX CHAR(3) NOT NULL,
                DESCRIPTIF TEXT NOT NULL,
                TAILLE VARCHAR NOT NULL,
                PRIMARY KEY (ID_PIZZA, ID_CATEGORIES, ID_RECETTES, NOM_INGRÉDIENTS, ID_EMPLOYES, ID_PIZZERIA, ADRESS_TRAVAIL)
);


CREATE TABLE PAIEMENT_INTERNE (
                SALAIRE INT NOT NULL,
                ID_EMPLOYES INT NOT NULL,
                DATE TIME NOT NULL,
                PRIMARY KEY (SALAIRE, ID_EMPLOYES)
);


CREATE TABLE Clients (
                ID INT AUTO_INCREMENT NOT NULL,
                passeword LONGNVARCHAR NOT NULL,
                TELEPHONE CHAR(10) NOT NULL,
                NOM VARCHAR(50) NOT NULL,
                PRENOM VARCHAR(50) NOT NULL,
                SEXE VARCHAR(10) NOT NULL,
                ADRESSE VARCHAR NOT NULL,
                PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX clients_idx
 ON Clients
 ( NOM );

CREATE TABLE FACTURE (
                ID VARCHAR NOT NULL,
                Clients_ID INT NOT NULL,
                DATE TIME NOT NULL,
                PRIX_TTC DECIMAL NOT NULL,
                PRIX_TOTAL INT NOT NULL,
                PRIMARY KEY (ID, Clients_ID)
);


CREATE TABLE LIVRAISON (
                ID_EXPEDITION INT NOT NULL,
                LIVREUR VARCHAR NOT NULL,
                ID_CLIENT INT NOT NULL,
                DATE DATETIME NOT NULL,
                PRIMARY KEY (ID_EXPEDITION, LIVREUR, ID_CLIENT)
);


CREATE TABLE VÉHICULE (
                ID_VÉHICULE VARCHAR NOT NULL,
                ID_EXPEDITION INT NOT NULL,
                LIVREUR VARCHAR NOT NULL,
                CLIENT_CIBLE INT NOT NULL,
                KILOMÉTRAGES INT NOT NULL,
                PRIMARY KEY (ID_VÉHICULE, ID_EXPEDITION, LIVREUR, CLIENT_CIBLE)
);


CREATE TABLE EMAIL (
                ID_CLIENT INT NOT NULL,
                EMAIL VARCHAR(60) NOT NULL,
                PRIMARY KEY (ID_CLIENT)
);


CREATE TABLE Commande (
                ID_CLIENT INT NOT NULL,
                FACTURE_ID VARCHAR NOT NULL,
                DATE_HEURE DATETIME NOT NULL,
                TYPE_PAIEMENT VARCHAR(10) NOT NULL,
                ETAT_COMMANDE VARCHAR NOT NULL,
                CODE_POSTAL CHAR(5) NOT NULL,
                ADRESSE VARCHAR NOT NULL,
                PIZZA VARCHAR(30) NOT NULL,
                ADRESSE_COMPLEMENTAIRE VARCHAR NOT NULL,
                RETARD VARCHAR NOT NULL,
                PRIMARY KEY (ID_CLIENT, FACTURE_ID)
);

ALTER TABLE Commande MODIFY COLUMN TYPE_PAIEMENT VARCHAR(10) COMMENT 'CB/ESPECES';
